AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  RedisCloudLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /RedisCloud/logs

  RedisCloudLogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: /RedisCloud/logs
      LogStreamName: RedisCloud-stream-logs
    DependsOn: RedisCloudLogGroup

  RedisCloudLogsSyncer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 300
      Handler: com.foogaro.aws.cloud.watch.lambda.handler.LogSyncHandler::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          CLOUDWATCH_LOG_GROUP: /RedisCloudLogsSyncer/logs
          CLOUDWATCH_LOG_STREAM: RedisCloudLogsSyncer-stream-logs
          REDIS_CLOUD_API_KEY: <REDIS_CLOUD_API_KEY>
          REDIS_CLOUD_API_SECRET: <REDIS_CLOUD_API_SECRET>
          REDIS_CLOUD_BATCH_SIZE: '5'
          REDIS_CLOUD_LOG_GROUP: /RedisCloud/logs
          REDIS_CLOUD_LOG_STREAM: RedisCloud-stream-logs
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Sid: CloudWatchLogsFullAccess
              Effect: Allow
              Action:
                - logs:*
                - cloudwatch:GenerateQuery
              Resource: '*'
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: rate(2 minutes)
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
    DependsOn: RedisCloudLogStream
